#!/usr/bin/env python3
"""
核心常量模块

提供项目中共享的常量定义，避免重复定义。

Usage:
    from core.constants import WEAK_SECRETS, KID_INJECTION_PAYLOADS
    from core.constants.security import WEAK_SECRETS
    from core.constants.kubernetes import DANGEROUS_CAPABILITIES
"""

from .kubernetes import (
    CONTAINER_RUNTIME_SOCKETS,
    CRITICAL_CAPABILITIES,
    DANGEROUS_CAPABILITIES,
    DANGEROUS_RBAC_RULES,
    DANGEROUS_VERBS,
    PSS_RESTRICTED_VIOLATIONS,
    RECOMMENDED_RESOURCE_LIMITS,
    RECOMMENDED_SECURITY_CONTEXT,
    SENSITIVE_MOUNT_PATHS,
    SENSITIVE_RESOURCES,
)
from .security import (
    COMMON_USER_AGENTS,
    DEFAULT_USER_AGENT,
    JKU_INJECTION_URLS,
    KID_INJECTION_PAYLOADS,
    NONE_ALGORITHM_VARIANTS,
    WEAK_SECRETS,
)

__all__ = [
    # Security
    "WEAK_SECRETS",
    "KID_INJECTION_PAYLOADS",
    "NONE_ALGORITHM_VARIANTS",
    "JKU_INJECTION_URLS",
    "COMMON_USER_AGENTS",
    "DEFAULT_USER_AGENT",
    # Kubernetes
    "DANGEROUS_CAPABILITIES",
    "CRITICAL_CAPABILITIES",
    "SENSITIVE_MOUNT_PATHS",
    "CONTAINER_RUNTIME_SOCKETS",
    "DANGEROUS_VERBS",
    "SENSITIVE_RESOURCES",
    "DANGEROUS_RBAC_RULES",
    "PSS_RESTRICTED_VIOLATIONS",
    "RECOMMENDED_SECURITY_CONTEXT",
    "RECOMMENDED_RESOURCE_LIMITS",
]
