"""扩展Payload库 - 600+ Payload库统一导出"""

from .sqli import ALL_SQLI, SQLI_ERROR, SQLI_UNION, SQLI_BLIND_BOOL, SQLI_BLIND_TIME, SQLI_WAF_BYPASS
from .xss import ALL_XSS, XSS_BASIC, XSS_EVENT_HANDLERS, XSS_ENCODED, XSS_WAF_BYPASS, XSS_DOM, XSS_POLYGLOT
from .lfi import ALL_LFI, LFI_BASIC, LFI_LINUX, LFI_WINDOWS, LFI_FILTER_BYPASS, PHP_WRAPPERS
from .rce import ALL_RCE, RCE_BASIC, RCE_LINUX, RCE_WINDOWS, RCE_BYPASS, RCE_OOB
from .ssrf import ALL_SSRF, SSRF_BASIC, CLOUD_METADATA, SSRF_PROTOCOLS, SSRF_BYPASS
from .xxe import ALL_XXE, XXE_BASIC, XXE_OOB, XXE_SSRF
from .ssti import ALL_SSTI, SSTI_DETECT, SSTI_JINJA2, SSTI_FREEMARKER, SSTI_TWIG
from .auth import DEFAULT_CREDS, WEAK_PASSWORDS, USERNAMES, AUTH_BYPASS, API_KEY_PATTERNS
from .online_sources import OnlinePayloadManager, NucleiTemplateManager

__all__ = [
    'ALL_SQLI', 'SQLI_ERROR', 'SQLI_UNION', 'SQLI_BLIND_BOOL', 'SQLI_BLIND_TIME', 'SQLI_WAF_BYPASS',
    'ALL_XSS', 'XSS_BASIC', 'XSS_EVENT_HANDLERS', 'XSS_ENCODED', 'XSS_WAF_BYPASS', 'XSS_DOM', 'XSS_POLYGLOT',
    'ALL_LFI', 'LFI_BASIC', 'LFI_LINUX', 'LFI_WINDOWS', 'LFI_FILTER_BYPASS', 'PHP_WRAPPERS',
    'ALL_RCE', 'RCE_BASIC', 'RCE_LINUX', 'RCE_WINDOWS', 'RCE_BYPASS', 'RCE_OOB',
    'ALL_SSRF', 'SSRF_BASIC', 'CLOUD_METADATA', 'SSRF_PROTOCOLS', 'SSRF_BYPASS',
    'ALL_XXE', 'XXE_BASIC', 'XXE_OOB', 'XXE_SSRF',
    'ALL_SSTI', 'SSTI_DETECT', 'SSTI_JINJA2', 'SSTI_FREEMARKER', 'SSTI_TWIG',
    'DEFAULT_CREDS', 'WEAK_PASSWORDS', 'USERNAMES', 'AUTH_BYPASS', 'API_KEY_PATTERNS',
    'OnlinePayloadManager', 'NucleiTemplateManager',
]
